<?php

session_start();
if($_SESSION["isLogin"] == true) {
    echo "<!DOCTYPE html>";
    echo "<html>";
    echo "<head>";
    echo "<meta name='viewport' content='width=device-width,initial-scale=1'>";
    echo "<link rel='stylesheet' href='includes/css/bootstrap.min.css'/>";
    echo "<link rel='stylesheet' href='includes/css/HeaderStyle.css'/>";
    echo "<link rel='stylesheet' href='includes/css/navMenu.css'/>";
    echo "<link rel='stylesheet' href='includes/css/rankingStars.css'/>";
    echo "<link rel='stylesheet' href='includes/css/mySpotGoogleMapStyle.css'/>";
    echo "<link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Noto+Sans:700'/>";
    echo "<link rel='stylesheet' href='http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>";
    echo "<script src='includes/js/jquery-2.1.4.min.js'></script>";
    echo "<script src='includes/js/mySpotGoogleMapScripts.js'></script>";
    echo "<script src='includes/js/logout.js'></script>";
    echo "<script src='includes/js/header.js'></script>";
    echo "<script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>";
    echo "<meta charset='UTF-8'>";
    echo "<meta http-equiv='content-type' content='text/html; charset=UTF-8'/>";
    echo "</head>";
    echo "<body>";
    echo "<div id='wrapper'>";
    echo "<header id='glbHeader'>";
    echo "<section id='logos-container'>";
    echo "<section id='userCont'>";
    echo "<a href='#' id='userPic'></a>";
    echo "<a href='#' id='logoutButton'>התנתק</a>";
    echo "</section>";
    echo "<a href='#' id='logo'></a>";
    echo "</section>";
    echo "<a href='#' id='hamburgerButton'></a>";
    echo "</header>";
    echo "<nav id='navMenu' class='navMenuState'>";
    echo "<ul id='menu'>";
    echo "<li class='firstNavLink'><a href='index.php'>דף הבית</a></li>";
    echo "<li><a href='spots.php' class='selected'>ספוטים</a></li>";
    echo "<li><a href='newspot.php'>הוסף ספוט</a></li>";
    echo "<li><a href='#'>עדכון תנאי חוף</a></li>";
    echo "<li><a href='#'>התראות</a></li>";
    echo "</ul>";
    echo "</nav>";
    echo "<div class='clear'></div>";
    echo "<section id='spotInfo'>";
    echo "<h2 id='spotName'></h2>";
    echo "<h3><span id='spotCity' class='txtInfo'></span><span id='spotRegion' class='txtInfo'></span></h3>";
    echo "</section>";
    echo "<br><br>";
    echo "<section id='map-container'>";
    echo "<div id='map'></div>";
    echo "</section>";
    echo "<div class='starsContainer'>";
    echo "<div class='stars'>";
    echo "<label class='star st1'></label>";
    echo "<label class='star st1'></label>";
    echo "<label class='star st1'></label>";
    echo "<label class='star st1'></label>";
    echo "<label class='star st1'></label>";
    echo "</div>";
    echo "</div>";
    echo "<section id='getDrvDirections'>";
    echo "<img src='includes/img/car.jpg' alt='car'>";
    echo "<a>קבל הוראות נסיעה</a>";
    echo "</section>";
    echo "<section id='waterInfo'>";
    echo "<img src='includes/img/wave-spotdetails.png' alt='car'>";
    echo "<h3 class='dataTxt paddedWaterInfo' id='waveHeight'></h3>";
    echo "<img src='includes/img/clock-spotdetails.png' alt='car'>";
    echo "<h3 class='dataTxt paddedWaterInfo' id='waveTiming'></h3>";
    echo "<img src='includes/img/tempratur-spotdetails.png' alt='car'>";
    echo "<img src='includes/img/celcius-spotdetails.png' alt='car'>";
    echo "<h3 class='dataTxt' id='waveTemp'></h3>";
    echo "</section>";
    echo "<section id='extendedSpotDetails'>";
    echo "<h2 id='extendedSpotDetailsHeader'>פרטי חוף</h2>";
    echo "<section id='extendedSpotDetailsBackground'>";
    echo "<section id='spotDataRightBlock'>";
    echo "<h4 class='spotDataKey'>רוח מיטבית</h4>";
    echo "<h2 class='spotDataValue' id='optWind'></h2>";
    echo "<h4 class='spotDataKey'>רמה ממולצת</h4>";
    echo "<h2 class='spotDataValue' id='level'>/p>";
    echo "<h4 class='spotDataKey'>עונה</h4>";
    echo "<h2 class='spotDataValue' id='season'></h2>";
    echo "<h4 class='spotDataKey'>סוג שבירה</h4>";
    echo "<h2 class='spotDataValue' id='waveBreakType'></h2>";
    echo "</section>";
    echo "<section id='spotDataLeftBlock'>";
    echo "<h4 class='spotDataKey'>סוג שבירה</h4>";
    echo "<h2 class='spotDataValue' id='waveBreakType2'></h2>";
    echo "<h4 class='spotDataKey'>כיוון שבירה</h4>";
    echo "<h2 class='spotDataValue' id='waveDirection'></h2>";
    echo "<h4 class='spotDataKey'>סוג תחתית</h4>";
    echo "<h2 class='spotDataValue' id='bottomType'></h2>";
    echo "<h4 class='spotDataKey'>גובה גל</h4>";
    echo "<h2 class='spotDataValue' id='waveHeightData'></h2>";
    echo "</section>";
    echo "</section>";
    echo "</section>";
    echo "<section id='posts'>";
    echo "</section>";
    echo "<div class='modal fade' id='directionsModal' role='dialog'>";
    echo "<div class='modal-dialog modal-lg'>";
    echo "<div class='modal-content'>";
    echo "<div class='modal-header'>";
    echo "<h4 class='modal-title' dir='rtl'>הוראות נסיעה לספוט מועדף</h4>";
    echo "</div>";
    echo "<div class='modal-body modal-lg'>";
    echo "<div id='drivingInstrucionsPanel'>";
    echo "<div id='directionsMap'></div>";
    echo "<div id='directionsPanel'></div>";
    echo "</div>";
    echo "</div>";
    echo "<div class='clear'></div>";
    echo "<div class='modal-footer'>";
    echo "<button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>";
    echo "</div>";
    echo "</div>";
    echo "</div>";
    echo "</div>";
    echo "<script async defer src='https://maps.googleapis.com/maps/api/js?key=AIzaSyAnmvaIGMxpoWZoXkIs_JCGoetynTVfCks&callback=mapDataManager'>";
    echo "</script>";
    echo "</div>";
    echo "</body>";
    echo "</html>";
}
else{
    readfile("includes/staticPages/403.html");
}
?>